/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg10115416_SistemInformasiApotek;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author 
     * Yayan Heryanto - 10115416
     * Iqbal Hasan - 10115567
     * Septa Farid Kurnia - 10115407
     * Nicko Novendestra - 10115257
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    boolean dataObat, dataKaryawan, dataSupplier, 
            dataPembelian, transaksiPenjualan, rumah;
    
    Koneksi dbsetting;
    String driver, database, user, pass; 
    
    JasperDesign jd;
    JasperReport rep;
    JasperPrint jp;
    
    public Admin() {                   
        initComponents();   
        
        dbsetting = new Koneksi();
        driver = dbsetting.settingPanel("DBDriver");
        database = dbsetting.settingPanel("DBDatabase");
        user = dbsetting.settingPanel("DBUsername");
        pass = dbsetting.settingPanel("DBPassword");
        
        this.setIconImage((Toolkit.getDefaultToolkit().getImage(getClass().getResource("/gambar/Logo.png"))));
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.pack();
        this.setSize(screenSize.width, screenSize.height);     
        
        getJam();
        
        try {
            Home frm = new Home();
            frm.setVisible(true);  
            this.jDesktopPane1.add(frm);
            frm.setMaximum(true);            
        } catch (PropertyVetoException e) {            
        }                 
    }  
    
    private void nonAktifMenu() {
        rumah = false;
        dataObat = false;
        dataKaryawan = false;
        dataSupplier = false;
        dataPembelian = false;
        transaksiPenjualan = false;
    }
    
    public void getJam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Locale id = new Locale("in", "ID");
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy", id);
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                Jam.setText("  " + jam + " : " + menit + " : " + detik + "  ");
                Tanggal.setText(tgl.format(dt));
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        data_obat = new javax.swing.JLabel();
        Data_Supplier = new javax.swing.JLabel();
        Transaksi_Penjualan = new javax.swing.JLabel();
        Data_Pembelian = new javax.swing.JLabel();
        Data_Karyawan = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Tanggal = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();
        menu_laporan = new javax.swing.JMenu();
        laporan_obat = new javax.swing.JMenuItem();
        laporan_karyawan = new javax.swing.JMenuItem();
        laporanSupplier = new javax.swing.JMenuItem();
        laporan_pembelian = new javax.swing.JMenuItem();
        laporan_penjualan = new javax.swing.JMenuItem();
        menu_about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apotek Avicenna");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        data_obat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        data_obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat.png"))); // NOI18N
        data_obat.setText("Obat");
        data_obat.setToolTipText("");
        data_obat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_obat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        data_obat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        data_obat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                data_obatMouseMoved(evt);
            }
        });
        data_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_obatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                data_obatMouseExited(evt);
            }
        });

        Data_Supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Data_Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/supplierIcon.png"))); // NOI18N
        Data_Supplier.setText("Supplier");
        Data_Supplier.setToolTipText("");
        Data_Supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Data_Supplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Data_Supplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Data_Supplier.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Data_SupplierMouseMoved(evt);
            }
        });
        Data_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Data_SupplierMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Data_SupplierMouseExited(evt);
            }
        });

        Transaksi_Penjualan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Transaksi_Penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penjualan.png"))); // NOI18N
        Transaksi_Penjualan.setText("Penjualan");
        Transaksi_Penjualan.setToolTipText("");
        Transaksi_Penjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Transaksi_Penjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Transaksi_Penjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Transaksi_Penjualan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Transaksi_PenjualanMouseMoved(evt);
            }
        });
        Transaksi_Penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Transaksi_PenjualanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Transaksi_PenjualanMouseExited(evt);
            }
        });

        Data_Pembelian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Data_Pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian.png"))); // NOI18N
        Data_Pembelian.setText("Pembelian");
        Data_Pembelian.setToolTipText("");
        Data_Pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Data_Pembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Data_Pembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Data_Pembelian.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Data_PembelianMouseMoved(evt);
            }
        });
        Data_Pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Data_PembelianMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Data_PembelianMouseExited(evt);
            }
        });

        Data_Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Data_Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/supplier.png"))); // NOI18N
        Data_Karyawan.setText("Karyawan");
        Data_Karyawan.setToolTipText("");
        Data_Karyawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Data_Karyawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Data_Karyawan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Data_Karyawan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Data_KaryawanMouseMoved(evt);
            }
        });
        Data_Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Data_KaryawanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Data_KaryawanMouseExited(evt);
            }
        });

        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        Home.setText("Home");
        Home.setToolTipText("");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeMouseMoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(data_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Data_Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Data_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Data_Pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Transaksi_Penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
            .addComponent(data_obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Data_Karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Data_Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Data_Pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Transaksi_Penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(240, 240, 255));

        jLabel6.setBackground(new java.awt.Color(240, 240, 255));
        jLabel6.setText("Pengguna Administrator");

        jPanel2.setBackground(new java.awt.Color(240, 240, 255));

        Tanggal.setText("Sabtu-22-Jul-2017");

        Jam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Jam.setText("17:16:20");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jam)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(Jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(null);

        menu_file.setBackground(new java.awt.Color(102, 102, 255));
        menu_file.setForeground(new java.awt.Color(255, 255, 255));
        menu_file.setText("File");
        menu_file.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_file.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_file.setIconTextGap(20);
        menu_file.setOpaque(true);
        menu_file.setPreferredSize(new java.awt.Dimension(60, 25));

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menu_file.add(menuKeluar);

        jMenuBar1.add(menu_file);

        menu_laporan.setText("Laporan");
        menu_laporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_laporan.setIconTextGap(9);
        menu_laporan.setPreferredSize(new java.awt.Dimension(60, 25));

        laporan_obat.setText("Laporan Obat");
        laporan_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_obatActionPerformed(evt);
            }
        });
        menu_laporan.add(laporan_obat);

        laporan_karyawan.setText("Laporan Karyawan");
        laporan_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_karyawanActionPerformed(evt);
            }
        });
        menu_laporan.add(laporan_karyawan);

        laporanSupplier.setText("Laporan Supplier");
        laporanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanSupplierActionPerformed(evt);
            }
        });
        menu_laporan.add(laporanSupplier);

        laporan_pembelian.setText("Laporan Pembelian");
        laporan_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_pembelianActionPerformed(evt);
            }
        });
        menu_laporan.add(laporan_pembelian);

        laporan_penjualan.setText("Laporan Penjualan");
        laporan_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_penjualanActionPerformed(evt);
            }
        });
        menu_laporan.add(laporan_penjualan);

        jMenuBar1.add(menu_laporan);

        menu_about.setBackground(new java.awt.Color(255, 255, 255));
        menu_about.setText("About");
        menu_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_about.setIconTextGap(13);
        menu_about.setPreferredSize(new java.awt.Dimension(60, 25));
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_obatMouseClicked
        // TODO add your handling code here:
        nonAktifMenu();
        dataObat = true;
        Data_Karyawan.setBackground(new Color(204,204,255));
        Home.setBackground(new Color(204,204,255));
        Data_Supplier.setBackground(new Color(204,204,255));
        Data_Pembelian.setBackground(new Color(204,204,255));
        Transaksi_Penjualan.setBackground(new Color(204,204,255));    
        
        dataObat obat = new dataObat();              
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(obat);           
        obat.setVisible(true);
        try {
            obat.setMaximum(true);            
        } catch (PropertyVetoException e) {
            
        }          
    }//GEN-LAST:event_data_obatMouseClicked

    private void Data_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_SupplierMouseClicked
        // TODO add your handling code here:  
        nonAktifMenu();
        dataSupplier = true;
        Data_Karyawan.setBackground(new Color(204,204,255));
        data_obat.setBackground(new Color(204,204,255));
        Home.setBackground(new Color(204,204,255));
        Data_Pembelian.setBackground(new Color(204,204,255));
        Transaksi_Penjualan.setBackground(new Color(204,204,255)); 
        
        dataSupplier Supplier = new dataSupplier();  
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(Supplier);            
        Supplier.setVisible(true);
        try {
            Supplier.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }//GEN-LAST:event_Data_SupplierMouseClicked

    private void Transaksi_PenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transaksi_PenjualanMouseClicked
        // TODO add your handling code here: 
        nonAktifMenu();
        transaksiPenjualan = true;
        Data_Karyawan.setBackground(new Color(204,204,255));
        data_obat.setBackground(new Color(204,204,255));
        Data_Supplier.setBackground(new Color(204,204,255));
        Data_Pembelian.setBackground(new Color(204,204,255));
        Home.setBackground(new Color(204,204,255));
        
        transaksiPenjualan Penjualan = new transaksiPenjualan();  
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(Penjualan);        
        Penjualan.show();
        try {
            Penjualan.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }//GEN-LAST:event_Transaksi_PenjualanMouseClicked

    private void Data_PembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_PembelianMouseClicked
        // TODO add your handling code here:
        nonAktifMenu();
        dataPembelian = true;
        Data_Karyawan.setBackground(new Color(204,204,255));
        data_obat.setBackground(new Color(204,204,255));
        Data_Supplier.setBackground(new Color(204,204,255));
        Home.setBackground(new Color(204,204,255));
        Transaksi_Penjualan.setBackground(new Color(204,204,255));
        
        dataPembelian Pembelian = new dataPembelian();  
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(Pembelian);        
        Pembelian.setVisible(true);
        try {
            Pembelian.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }//GEN-LAST:event_Data_PembelianMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        nonAktifMenu();
        rumah = true;
        Data_Karyawan.setBackground(new Color(204,204,255));
        data_obat.setBackground(new Color(204,204,255));
        Data_Supplier.setBackground(new Color(204,204,255));
        Data_Pembelian.setBackground(new Color(204,204,255));
        Transaksi_Penjualan.setBackground(new Color(204,204,255));
        
        Home home = new Home();  
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(home);        
        home.setVisible(true);
        try {
            home.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }//GEN-LAST:event_HomeMouseClicked

    private void Data_KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_KaryawanMouseClicked
        // TODO add your handling code here:
        nonAktifMenu();
        dataKaryawan = true;         
        Home.setBackground(new Color(204,204,255));
        data_obat.setBackground(new Color(204,204,255));
        Data_Supplier.setBackground(new Color(204,204,255));
        Data_Pembelian.setBackground(new Color(204,204,255));
        Transaksi_Penjualan.setBackground(new Color(204,204,255));
        
        dataKaryawan Karyawan = new dataKaryawan();  
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(Karyawan);        
        Karyawan.setVisible(true);
        try {
            Karyawan.setMaximum(true);
        } catch (PropertyVetoException e) {
            
        }
    }//GEN-LAST:event_Data_KaryawanMouseClicked

    private void HomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseMoved
        // TODO add your handling code here:
        Home.setOpaque(true);
        Home.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_HomeMouseMoved

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        // TODO add your handling code here:
        Home.setOpaque(true);
        if (rumah == true) {
            Home.setBackground(new Color(240,240,255));
        } else {
            Home.setBackground(new Color(204,204,255));
        } 
    }//GEN-LAST:event_HomeMouseExited

    private void data_obatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_obatMouseMoved
        // TODO add your handling code here:
        data_obat.setOpaque(true);
        data_obat.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_data_obatMouseMoved

    private void data_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_obatMouseExited
        // TODO add your handling code here:
        data_obat.setOpaque(true);
        if (dataObat == true) {
            data_obat.setBackground(new Color(240,240,255));
        } else {
            data_obat.setBackground(new Color(204,204,255));
        }          
    }//GEN-LAST:event_data_obatMouseExited

    private void Data_KaryawanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_KaryawanMouseMoved
        // TODO add your handling code here:
        Data_Karyawan.setOpaque(true);
        Data_Karyawan.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_Data_KaryawanMouseMoved

    private void Data_KaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_KaryawanMouseExited
        // TODO add your handling code here:
        Data_Karyawan.setOpaque(true);
        if (dataKaryawan == true) {
            Data_Karyawan.setBackground(new Color(240,240,255));
        } else {
            Data_Karyawan.setBackground(new Color(204,204,255));            
        }
    }//GEN-LAST:event_Data_KaryawanMouseExited

    private void Data_SupplierMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_SupplierMouseMoved
        // TODO add your handling code here:
        Data_Supplier.setOpaque(true);
        Data_Supplier.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_Data_SupplierMouseMoved

    private void Data_SupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_SupplierMouseExited
        // TODO add your handling code here:
        Data_Supplier.setOpaque(true);
        if (dataSupplier == true) {
            Data_Supplier.setBackground(new Color(240,240,255));
        } else {
            Data_Supplier.setBackground(new Color(204,204,255));
        } 
    }//GEN-LAST:event_Data_SupplierMouseExited

    private void Data_PembelianMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_PembelianMouseMoved
        // TODO add your handling code here:
        Data_Pembelian.setOpaque(true);
        Data_Pembelian.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_Data_PembelianMouseMoved

    private void Data_PembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Data_PembelianMouseExited
        // TODO add your handling code here:
        Data_Pembelian.setOpaque(true);
        if (dataPembelian == true) {
            Data_Pembelian.setBackground(new Color(240,240,255));
        } else {
            Data_Pembelian.setBackground(new Color(204,204,255));
        } 
    }//GEN-LAST:event_Data_PembelianMouseExited

    private void Transaksi_PenjualanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transaksi_PenjualanMouseMoved
        // TODO add your handling code here:
        Transaksi_Penjualan.setOpaque(true);
        Transaksi_Penjualan.setBackground(new Color(240,240,255));
    }//GEN-LAST:event_Transaksi_PenjualanMouseMoved

    private void Transaksi_PenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transaksi_PenjualanMouseExited
        // TODO add your handling code here:
        Transaksi_Penjualan.setOpaque(true);
        if (transaksiPenjualan == true) {
            Transaksi_Penjualan.setBackground(new Color(240,240,255));
        } else {
            Transaksi_Penjualan.setBackground(new Color(204,204,255));
        } 
    }//GEN-LAST:event_Transaksi_PenjualanMouseExited

    private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
        // TODO add your handling code here:    
        try {
            FormAbout about = new FormAbout(null, true);
            about.pack();
            about.setLocationRelativeTo(this);
            about.setVisible(true);            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_menu_aboutMouseClicked

    private void laporan_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_obatActionPerformed
        // TODO add your handling code here:
        Map<String, Object> kode_obat = new HashMap<String, Object>();
        try {
            // TODO add your handling code here:
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            //File file = new File("src/laporan/laporan_obat.jrxml");
            InputStream file = getClass().getResourceAsStream("/laporan/laporan_obat.jrxml");
            jd = JRXmlLoader.load(file);
            rep = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(rep, kode_obat, kon);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_laporan_obatActionPerformed

    private void laporan_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_karyawanActionPerformed
        // TODO add your handling code here:
        Map<String, Object> id_karyawan = new HashMap<String, Object>();
        try {
            // TODO add your handling code here:
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            //File file = new File("src/laporan/laporan_karyawan.jrxml");
            InputStream file = getClass().getResourceAsStream("/laporan/laporan_karyawan.jrxml");
            jd = JRXmlLoader.load(file);
            rep = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(rep, id_karyawan, kon);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_laporan_karyawanActionPerformed

    private void laporanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanSupplierActionPerformed
        // TODO add your handling code here:
        Map<String, Object> id_suplier = new HashMap<String, Object>();
        try {
            // TODO add your handling code here:
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            //File file = new File("src/laporan/laporan_suplier.jrxml");
            InputStream file = getClass().getResourceAsStream("/laporan/laporan_suplier.jrxml");
            jd = JRXmlLoader.load(file);
            rep = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(rep, id_suplier, kon);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dataObat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_laporanSupplierActionPerformed

    private void laporan_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_pembelianActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Map<String, Object> id_pembelian = new HashMap<String, Object>();
            
            // TODO add your handling code here:
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            //File file = new File("src/laporan/laporan_pembelian.jrxml");
            InputStream file = getClass().getResourceAsStream("/laporan/laporan_pembelian.jrxml");
            jd = JRXmlLoader.load(file);
            rep = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(rep, id_pembelian, kon);
            JasperViewer.viewReport(jp, false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_laporan_pembelianActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.pack();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void laporan_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_penjualanActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Map<String, Object> id_penjualan = new HashMap<String, Object>();
            
            // TODO add your handling code here:
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database, user, pass);
            
            //File file = new File("src/laporan/laporan_penjualan.jrxml");
            InputStream file = getClass().getResourceAsStream("/laporan/laporan_penjualan.jrxml");
            jd = JRXmlLoader.load(file);
            rep = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(rep, id_penjualan, kon);
            JasperViewer.viewReport(jp, false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_laporan_penjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data_Karyawan;
    private javax.swing.JLabel Data_Pembelian;
    private javax.swing.JLabel Data_Supplier;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Jam;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Transaksi_Penjualan;
    private javax.swing.JLabel data_obat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenuItem laporanSupplier;
    private javax.swing.JMenuItem laporan_karyawan;
    private javax.swing.JMenuItem laporan_obat;
    private javax.swing.JMenuItem laporan_pembelian;
    private javax.swing.JMenuItem laporan_penjualan;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_laporan;
    // End of variables declaration//GEN-END:variables
}
